package GUI;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;


public class QRDialog extends javax.swing.JDialog {

    BufferedImage bufferedImage;
    /**
     * Creates new form QRDialog
     */
    public QRDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("QR");
        jLabel1.setText("");
        jLabel1.setToolTipText("Click para guardar");
        setLocationRelativeTo(null);        
        setBackground(Color.white);
    }

    public void setImageQR(BufferedImage bufferedImage)
    {
        if(bufferedImage!=null)
        {
            this.bufferedImage = bufferedImage;
            ImageIcon icon = new ImageIcon(bufferedImage);            
            setSize(icon.getIconWidth()+20,icon.getIconHeight()+40);
            jLabel1.setIcon( icon );                        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar QR");
        FileFilter filter = new FileNameExtensionFilter("QR Image", "PNG");
        fileChooser.addChoosableFileFilter(filter);
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION)
        {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.toString().endsWith(".png"))
            {
             fileToSave = new File(fileChooser.getSelectedFile()+".png");
            }
            try {            
                ImageIO.write(bufferedImage, "png", fileToSave);
            } catch (IOException ex) {
                System.err.println( ex.getMessage() );
            }
            dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
