/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBConnection;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author THE-BCD
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    
    DBConnection dbC;
    public Reportes() {
        initComponents();

        // jPanel1.setVisible(false);
        //jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jDateChooserDiaFin.setVisible(false);
        jLabel2.setVisible(false);
        //jLayeredPane1.setLayer(this, WIDTH);
        //this.pack();
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        dbC = new DBConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jLabel4 = new javax.swing.JLabel();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserDiaInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserDiaFin = new com.toedter.calendar.JDateChooser();
        reportBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Desayuno", "Comida", "Cena", "Colacion" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "Semana", "Mes", "Año" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 3, 5));

        jLabel3.setText("Mes:");
        jPanel3.add(jLabel3);
        jPanel3.add(jMonthChooser);

        jLabel4.setText("Año:");
        jPanel3.add(jLabel4);
        jPanel3.add(jYearChooser);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 8));

        jLabel1.setText("Fecha Inicio:");
        jPanel2.add(jLabel1);
        jPanel2.add(jDateChooserDiaInicio);

        jLabel2.setText("Fecha Final:");
        jPanel2.add(jLabel2);
        jPanel2.add(jDateChooserDiaFin);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        reportBtn.setText("Ver Reporte");
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(msgLabel)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgLabel)
                .addGap(3, 3, 3)
                .addComponent(reportBtn)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

        int op = jComboBox2.getSelectedIndex();

        switch (op) {

            case 0:
                //jPanel1.setVisible(true);
                jPanel2.setVisible(true);
                jDateChooserDiaFin.setVisible(false);
                jLabel2.setVisible(false);
                jPanel3.setVisible(false);
                //jPanel4.setVisible(false);
                break;

            case 1:
                //jPanel1.setVisible(false);
                jPanel2.setVisible(true);
                jDateChooserDiaFin.setVisible(true);
                jLabel2.setVisible(true);
                jPanel3.setVisible(false);
                //jPanel4.setVisible(false);
                break;

            case 2:
                //jPanel1.setVisible(false);
                jPanel2.setVisible(false);
                jMonthChooser.setVisible(true);
                jLabel3.setVisible(true);
                jPanel3.setVisible(true);
                //jPanel4.setVisible(false);
                break;

            case 3:
                //jPanel1.setVisible(false);
                jPanel2.setVisible(false);
                jMonthChooser.setVisible(false);
                jLabel3.setVisible(false);
                jPanel3.setVisible(true);
                break;
            default:
                //error
        }

        //this.pack();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        String que = jComboBox1.getSelectedItem().toString();
        String como = jComboBox2.getSelectedItem().toString();
        String reporte = "";
        System.out.println("Opciones " + que + " : " + como);
        
        int op = jComboBox2.getSelectedIndex();
        String where ="";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        switch(op){
            case 0://Un dia
                String dt = sdf.format(jDateChooserDiaInicio.getDate());
                System.out.println(dt);
                where = "WHERE DATE(horaComida) = \""+ dt+"\" ";
                
                break;
            case 1://De una fecha a otra fecha
                String dtI = sdf.format(jDateChooserDiaInicio.getDate());
                String dtF = sdf.format(jDateChooserDiaFin.getDate());
                System.out.println(dtI + " a " + dtF);
                where = "WHERE DATE(horaComida) >= \""+ dtI +"\" "+
                        "AND DATE(horaComida) <= \"" + dtF +"\"";
                break;
            case 2://Un mes
                int month = jMonthChooser.getMonth() + 1;
                System.out.println(month+"/"+jYearChooser.getYear());
                where = "WHERE MONTH(horaComida) = " + month +
                        " AND YEAR(horaComida) = " + jYearChooser.getYear();
                break;
            case 3:// Un año
                where = "WHERE YEAR(horaComida) = " + jYearChooser.getYear();
                break;
        }
        
        if(jComboBox1.getSelectedIndex() != 0)
                    where += " AND comida = \""+que+" \" ";
        
        String report = dbC.getReporte(where);
        saveTheReport(report);
        //System.out.println(report);
        
    }//GEN-LAST:event_reportBtnActionPerformed

    private void saveTheReport(String report){
        JFileChooser chooser = new JFileChooser();
        
        chooser.setDialogTitle("Guardar como: ");
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File fl = chooser.getSelectedFile();
            
            //String dir = chooser.getSelectedFile().toString();
            System.out.println("Guardar en: " + fl+".txt");
            try {
                PrintWriter writer = new PrintWriter(fl+".txt", "UTF-8");
                writer.write(report);
                writer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            msgLabel.setText("Reporte guardado en " + fl);
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dbC.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooserDiaFin;
    private com.toedter.calendar.JDateChooser jDateChooserDiaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton reportBtn;
    // End of variables declaration//GEN-END:variables
}
